// Generated by CoffeeScript 1.6.3
(function() {
  var picker_code;

  picker_code = "<div class='picker' style='display: none;'><div class='color-map'><div class='pointer'></div></div><div class='saturation'><div class='selector'></div></div></div>";

  $.fn.colorPicker = function(action) {
    if (!action) {
      this.each(function() {
        var moving, p, startmove, stopmove;
        if (!$(this).next().hasClass("picker")) {
          p = $(picker_code);
          p.click(function(e) {
            return e.stopPropagation();
          });
          startmove = function(e, r, t) {
            var pointer, x, y;
            x = e.offsetX !== null ? e.offsetX : e.originalEvent.layerX;
            y = e.offsetY !== null ? e.offsetY : e.originalEvent.layerY;
            pointer = $(".pointer:visible");
            pointer.css("top", y + "px");
            pointer.css("left", x + "px");
            return $(document).on({
              mouseover: moving,
              mousemove: moving
            });
          };
          moving = function(e) {
            var pointer, x, y;
            x = e.offsetX !== null ? e.offsetX : e.originalEvent.layerX;
            y = e.offsetY !== null ? e.offsetY : e.originalEvent.layerY;
            pointer = $(".pointer:visible");
            pointer.css("top", y + "px");
            return pointer.css("left", x + "px");
          };
          stopmove = function(e) {
            var pointer, x, y;
            pointer = $(".pointer:visible");
            x = e.offsetX !== null ? e.offsetX : e.originalEvent.layerX;
            y = e.offsetY !== null ? e.offsetY : e.originalEvent.layerY;
            $(document).off({
              mouseover: moving,
              mousemove: moving
            });
            pointer.css("top", y + "px");
            return pointer.css("left", x + "px");
          };
          p.find(".color-map").on({
            mousedown: startmove,
            mouseup: stopmove
          });
          return $(this).after(p);
        }
      });
      $("body").on("click", ".colorpicker", function(e) {
        var p;
        p = $(this).next();
        if (p.is(":visible")) {
          return;
        }
        $(".picker").each(function() {
          if ((p[0] !== $(this)[0]) && ($(this).is(":visible"))) {
            return $(this).hide();
          }
        });
        p.css("top", $(this).position().top + $(this).outerHeight(true));
        p.css("left", $(this).position().left + parseInt($(this).css("margin-left"), 10));
        p.toggle();
        return e.stopPropagation();
      });
      $(document).click(function() {
        return $(".picker:visible").hide();
      });
    }
    return this;
  };

  $(".colorpicker").colorPicker();

}).call(this);
